<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;


class Theme extends ActiveRecord
{

    public static function tableName()
    {
        return 'theme'; // TODO: Change the autogenerated stub
    }

    public function getThemes()
    {
        return self::find()->all();
    }

}